  name: 'Get & Cache Dependencies'
  description: 'Get the dependencies (via npm) and cache them'
  runs:
      using: 'composite'
      steps:
          - name: Cache dependencies
            uses: actions/cache@v3
            with:
                path: ~/.npm
                key: npm-deps-${{ hashFiles('**/package-lock.json') }}
          - name: Install dependencies
            run: npm ci
            shell: bash

